{"failed_row": {"id": 4, "email": "stvxdkxwnmukaimlpg@hthlm.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873521+00:00", "updated_at": "2024-11-26 12:40:15.873522+00:00", "created_at": "2024-11-26 12:40:15.873523+00:00", "invitation_accepted": true, "organization_id": "025fc7c3-ff00-4d97-b5b3-6fbe866ca493", "user_id": "5"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(025fc7c3-ff00-4d97-b5b3-6fbe866ca493, stvxdkxwnmukaimlpg@hthlm.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(025fc7c3-ff00-4d97-b5b3-6fbe866ca493, stvxdkxwnmukaimlpg@hthlm.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 6, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873529+00:00", "updated_at": "2024-11-26 12:40:15.873530+00:00", "created_at": "2024-11-26 12:40:15.873532+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 7, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873535+00:00", "updated_at": "2024-11-26 12:40:15.873536+00:00", "created_at": "2024-11-26 12:40:15.873537+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 8, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873539+00:00", "updated_at": "2024-11-26 12:40:15.873540+00:00", "created_at": "2024-11-26 12:40:15.873541+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 9, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873544+00:00", "updated_at": "2024-11-26 12:40:15.873546+00:00", "created_at": "2024-11-26 12:40:15.873547+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 10, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873549+00:00", "updated_at": "2024-11-26 12:40:15.873550+00:00", "created_at": "2024-11-26 12:40:15.873551+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 11, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873553+00:00", "updated_at": "2024-11-26 12:40:15.873554+00:00", "created_at": "2024-11-26 12:40:15.873555+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 12, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873557+00:00", "updated_at": "2024-11-26 12:40:15.873558+00:00", "created_at": "2024-11-26 12:40:15.873560+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 13, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873561+00:00", "updated_at": "2024-11-26 12:40:15.873562+00:00", "created_at": "2024-11-26 12:40:15.873564+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 14, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873565+00:00", "updated_at": "2024-11-26 12:40:15.873567+00:00", "created_at": "2024-11-26 12:40:15.873568+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 15, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873569+00:00", "updated_at": "2024-11-26 12:40:15.873571+00:00", "created_at": "2024-11-26 12:40:15.873572+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 16, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873574+00:00", "updated_at": "2024-11-26 12:40:15.873575+00:00", "created_at": "2024-11-26 12:40:15.873576+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 17, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873578+00:00", "updated_at": "2024-11-26 12:40:15.873579+00:00", "created_at": "2024-11-26 12:40:15.873580+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 18, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873582+00:00", "updated_at": "2024-11-26 12:40:15.873583+00:00", "created_at": "2024-11-26 12:40:15.873584+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 19, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873586+00:00", "updated_at": "2024-11-26 12:40:15.873587+00:00", "created_at": "2024-11-26 12:40:15.873588+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 20, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873593+00:00", "updated_at": "2024-11-26 12:40:15.873594+00:00", "created_at": "2024-11-26 12:40:15.873595+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 21, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873597+00:00", "updated_at": "2024-11-26 12:40:15.873598+00:00", "created_at": "2024-11-26 12:40:15.873600+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 22, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873601+00:00", "updated_at": "2024-11-26 12:40:15.873603+00:00", "created_at": "2024-11-26 12:40:15.873604+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 23, "email": "aashu.0704@zohomail.in", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873605+00:00", "updated_at": "2024-11-26 12:40:15.873609+00:00", "created_at": "2024-11-26 12:40:15.873610+00:00", "invitation_accepted": true, "organization_id": "d6c74e6c-2039-4df2-8e68-646e262efd96", "user_id": "6"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(d6c74e6c-2039-4df2-8e68-646e262efd96, aashu.0704@zohomail.in) already exists.\n\n"}
-----|10
{"failed_row": {"id": 27, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873625+00:00", "updated_at": "2024-11-26 12:40:15.873626+00:00", "created_at": "2024-11-26 12:40:15.873627+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 28, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873629+00:00", "updated_at": "2024-11-26 12:40:15.873630+00:00", "created_at": "2024-11-26 12:40:15.873631+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 29, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873633+00:00", "updated_at": "2024-11-26 12:40:15.873634+00:00", "created_at": "2024-11-26 12:40:15.873635+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 30, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873637+00:00", "updated_at": "2024-11-26 12:40:15.873638+00:00", "created_at": "2024-11-26 12:40:15.873640+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 31, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873641+00:00", "updated_at": "2024-11-26 12:40:15.873643+00:00", "created_at": "2024-11-26 12:40:15.873644+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 32, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873646+00:00", "updated_at": "2024-11-26 12:40:15.873647+00:00", "created_at": "2024-11-26 12:40:15.873648+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 33, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873650+00:00", "updated_at": "2024-11-26 12:40:15.873651+00:00", "created_at": "2024-11-26 12:40:15.873652+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 34, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873655+00:00", "updated_at": "2024-11-26 12:40:15.873657+00:00", "created_at": "2024-11-26 12:40:15.873658+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 35, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873660+00:00", "updated_at": "2024-11-26 12:40:15.873661+00:00", "created_at": "2024-11-26 12:40:15.873662+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 36, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873664+00:00", "updated_at": "2024-11-26 12:40:15.873665+00:00", "created_at": "2024-11-26 12:40:15.873666+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 37, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873668+00:00", "updated_at": "2024-11-26 12:40:15.873669+00:00", "created_at": "2024-11-26 12:40:15.873672+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 38, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873674+00:00", "updated_at": "2024-11-26 12:40:15.873675+00:00", "created_at": "2024-11-26 12:40:15.873677+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 39, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873678+00:00", "updated_at": "2024-11-26 12:40:15.873679+00:00", "created_at": "2024-11-26 12:40:15.873681+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 40, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873682+00:00", "updated_at": "2024-11-26 12:40:15.873684+00:00", "created_at": "2024-11-26 12:40:15.873685+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 41, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873687+00:00", "updated_at": "2024-11-26 12:40:15.873688+00:00", "created_at": "2024-11-26 12:40:15.873690+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 42, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873692+00:00", "updated_at": "2024-11-26 12:40:15.873693+00:00", "created_at": "2024-11-26 12:40:15.873695+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 43, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873696+00:00", "updated_at": "2024-11-26 12:40:15.873698+00:00", "created_at": "2024-11-26 12:40:15.873699+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 44, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873701+00:00", "updated_at": "2024-11-26 12:40:15.873702+00:00", "created_at": "2024-11-26 12:40:15.873704+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 45, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873705+00:00", "updated_at": "2024-11-26 12:40:15.873707+00:00", "created_at": "2024-11-26 12:40:15.873708+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 46, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873710+00:00", "updated_at": "2024-11-26 12:40:15.873711+00:00", "created_at": "2024-11-26 12:40:15.873712+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 47, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873715+00:00", "updated_at": "2024-11-26 12:40:15.873717+00:00", "created_at": "2024-11-26 12:40:15.873718+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 48, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873720+00:00", "updated_at": "2024-11-26 12:40:15.873721+00:00", "created_at": "2024-11-26 12:40:15.873723+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 49, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873724+00:00", "updated_at": "2024-11-26 12:40:15.873726+00:00", "created_at": "2024-11-26 12:40:15.873727+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 50, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873728+00:00", "updated_at": "2024-11-26 12:40:15.873730+00:00", "created_at": "2024-11-26 12:40:15.873731+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 51, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873733+00:00", "updated_at": "2024-11-26 12:40:15.873734+00:00", "created_at": "2024-11-26 12:40:15.873737+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 52, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873738+00:00", "updated_at": "2024-11-26 12:40:15.873740+00:00", "created_at": "2024-11-26 12:40:15.873741+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 53, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873742+00:00", "updated_at": "2024-11-26 12:40:15.873744+00:00", "created_at": "2024-11-26 12:40:15.873745+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 54, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873747+00:00", "updated_at": "2024-11-26 12:40:15.873748+00:00", "created_at": "2024-11-26 12:40:15.873749+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 55, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873751+00:00", "updated_at": "2024-11-26 12:40:15.873752+00:00", "created_at": "2024-11-26 12:40:15.873754+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 56, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873755+00:00", "updated_at": "2024-11-26 12:40:15.873757+00:00", "created_at": "2024-11-26 12:40:15.873758+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 57, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873760+00:00", "updated_at": "2024-11-26 12:40:15.873761+00:00", "created_at": "2024-11-26 12:40:15.873762+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 58, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873764+00:00", "updated_at": "2024-11-26 12:40:15.873765+00:00", "created_at": "2024-11-26 12:40:15.873766+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 59, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873768+00:00", "updated_at": "2024-11-26 12:40:15.873769+00:00", "created_at": "2024-11-26 12:40:15.873771+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 60, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873774+00:00", "updated_at": "2024-11-26 12:40:15.873776+00:00", "created_at": "2024-11-26 12:40:15.873778+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 61, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873779+00:00", "updated_at": "2024-11-26 12:40:15.873781+00:00", "created_at": "2024-11-26 12:40:15.873782+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 62, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873783+00:00", "updated_at": "2024-11-26 12:40:15.873785+00:00", "created_at": "2024-11-26 12:40:15.873786+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 63, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873788+00:00", "updated_at": "2024-11-26 12:40:15.873789+00:00", "created_at": "2024-11-26 12:40:15.873790+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 64, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873792+00:00", "updated_at": "2024-11-26 12:40:15.873793+00:00", "created_at": "2024-11-26 12:40:15.873794+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 65, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873796+00:00", "updated_at": "2024-11-26 12:40:15.873797+00:00", "created_at": "2024-11-26 12:40:15.873800+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 66, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873802+00:00", "updated_at": "2024-11-26 12:40:15.873803+00:00", "created_at": "2024-11-26 12:40:15.873804+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 67, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873806+00:00", "updated_at": "2024-11-26 12:40:15.873807+00:00", "created_at": "2024-11-26 12:40:15.873808+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 68, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873810+00:00", "updated_at": "2024-11-26 12:40:15.873811+00:00", "created_at": "2024-11-26 12:40:15.873813+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 69, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873814+00:00", "updated_at": "2024-11-26 12:40:15.873815+00:00", "created_at": "2024-11-26 12:40:15.873817+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 70, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873818+00:00", "updated_at": "2024-11-26 12:40:15.873820+00:00", "created_at": "2024-11-26 12:40:15.873821+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 71, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873823+00:00", "updated_at": "2024-11-26 12:40:15.873824+00:00", "created_at": "2024-11-26 12:40:15.873825+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 72, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873827+00:00", "updated_at": "2024-11-26 12:40:15.873829+00:00", "created_at": "2024-11-26 12:40:15.873830+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 73, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873833+00:00", "updated_at": "2024-11-26 12:40:15.873834+00:00", "created_at": "2024-11-26 12:40:15.873835+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 74, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873837+00:00", "updated_at": "2024-11-26 12:40:15.873838+00:00", "created_at": "2024-11-26 12:40:15.873839+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 75, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873841+00:00", "updated_at": "2024-11-26 12:40:15.873842+00:00", "created_at": "2024-11-26 12:40:15.873844+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 76, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873847+00:00", "updated_at": "2024-11-26 12:40:15.873848+00:00", "created_at": "2024-11-26 12:40:15.873849+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 77, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873851+00:00", "updated_at": "2024-11-26 12:40:15.873852+00:00", "created_at": "2024-11-26 12:40:15.873853+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 78, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873855+00:00", "updated_at": "2024-11-26 12:40:15.873857+00:00", "created_at": "2024-11-26 12:40:15.873858+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 79, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873860+00:00", "updated_at": "2024-11-26 12:40:15.873861+00:00", "created_at": "2024-11-26 12:40:15.873862+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 80, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873865+00:00", "updated_at": "2024-11-26 12:40:15.873867+00:00", "created_at": "2024-11-26 12:40:15.873868+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 81, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873870+00:00", "updated_at": "2024-11-26 12:40:15.873871+00:00", "created_at": "2024-11-26 12:40:15.873872+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 82, "email": "ankita11habilelabs@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873874+00:00", "updated_at": "2024-11-26 12:40:15.873875+00:00", "created_at": "2024-11-26 12:40:15.873877+00:00", "invitation_accepted": true, "organization_id": "a8141b4d-02e4-45cf-b703-e3099ba82c10", "user_id": "12"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(a8141b4d-02e4-45cf-b703-e3099ba82c10, ankita11habilelabs@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 86, "email": "jk1282002@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873891+00:00", "updated_at": "2024-11-26 12:40:15.873892+00:00", "created_at": "2024-11-26 12:40:15.873894+00:00", "invitation_accepted": true, "organization_id": "f1bbc8fa-0021-4b7b-861f-25bd3a19e890", "user_id": "19"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890, jk1282002@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890, jk1282002@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 87, "email": "jk1282002@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873896+00:00", "updated_at": "2024-11-26 12:40:15.873898+00:00", "created_at": "2024-11-26 12:40:15.873899+00:00", "invitation_accepted": true, "organization_id": "f1bbc8fa-0021-4b7b-861f-25bd3a19e890", "user_id": "19"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890, jk1282002@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890, jk1282002@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 88, "email": "jk1282002@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873901+00:00", "updated_at": "2024-11-26 12:40:15.873902+00:00", "created_at": "2024-11-26 12:40:15.873915+00:00", "invitation_accepted": true, "organization_id": "f1bbc8fa-0021-4b7b-861f-25bd3a19e890", "user_id": "19"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890, jk1282002@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890, jk1282002@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 89, "email": "jk1282002@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873917+00:00", "updated_at": "2024-11-26 12:40:15.873940+00:00", "created_at": "2024-11-26 12:40:15.873941+00:00", "invitation_accepted": true, "organization_id": "f1bbc8fa-0021-4b7b-861f-25bd3a19e890", "user_id": "19"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890, jk1282002@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(f1bbc8fa-0021-4b7b-861f-25bd3a19e890, jk1282002@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 91, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873948+00:00", "updated_at": "2024-11-26 12:40:15.873949+00:00", "created_at": "2024-11-26 12:40:15.873951+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 92, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873956+00:00", "updated_at": "2024-11-26 12:40:15.873957+00:00", "created_at": "2024-11-26 12:40:15.873959+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 93, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873961+00:00", "updated_at": "2024-11-26 12:40:15.873962+00:00", "created_at": "2024-11-26 12:40:15.873964+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 94, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873966+00:00", "updated_at": "2024-11-26 12:40:15.873968+00:00", "created_at": "2024-11-26 12:40:15.873970+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 95, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873972+00:00", "updated_at": "2024-11-26 12:40:15.873973+00:00", "created_at": "2024-11-26 12:40:15.873974+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 96, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873976+00:00", "updated_at": "2024-11-26 12:40:15.873978+00:00", "created_at": "2024-11-26 12:40:15.873979+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 97, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873994+00:00", "updated_at": "2024-11-26 12:40:15.873996+00:00", "created_at": "2024-11-26 12:40:15.873997+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 98, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.873999+00:00", "updated_at": "2024-11-26 12:40:15.874000+00:00", "created_at": "2024-11-26 12:40:15.874001+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 99, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874003+00:00", "updated_at": "2024-11-26 12:40:15.874004+00:00", "created_at": "2024-11-26 12:40:15.874005+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 100, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874013+00:00", "updated_at": "2024-11-26 12:40:15.874015+00:00", "created_at": "2024-11-26 12:40:15.874016+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 101, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874018+00:00", "updated_at": "2024-11-26 12:40:15.874019+00:00", "created_at": "2024-11-26 12:40:15.874020+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 102, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874022+00:00", "updated_at": "2024-11-26 12:40:15.874023+00:00", "created_at": "2024-11-26 12:40:15.874024+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 103, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874026+00:00", "updated_at": "2024-11-26 12:40:15.874027+00:00", "created_at": "2024-11-26 12:40:15.874029+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 104, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874030+00:00", "updated_at": "2024-11-26 12:40:15.874032+00:00", "created_at": "2024-11-26 12:40:15.874033+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 105, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874035+00:00", "updated_at": "2024-11-26 12:40:15.874036+00:00", "created_at": "2024-11-26 12:40:15.874037+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 106, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874039+00:00", "updated_at": "2024-11-26 12:40:15.874040+00:00", "created_at": "2024-11-26 12:40:15.874041+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 107, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874043+00:00", "updated_at": "2024-11-26 12:40:15.874044+00:00", "created_at": "2024-11-26 12:40:15.874046+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 108, "email": "a21kanjolia@gmail.com", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874049+00:00", "updated_at": "2024-11-26 12:40:15.874051+00:00", "created_at": "2024-11-26 12:40:15.874053+00:00", "invitation_accepted": true, "organization_id": "29d9a918-9e5f-4f69-96fa-e212305c1b31", "user_id": "21"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(29d9a918-9e5f-4f69-96fa-e212305c1b31, a21kanjolia@gmail.com) already exists.\n\n"}
-----|10
{"failed_row": {"id": 116, "email": "shreya@habilelabs.io", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874085+00:00", "updated_at": "2024-11-26 12:40:15.874087+00:00", "created_at": "2024-11-26 12:40:15.874088+00:00", "invitation_accepted": true, "organization_id": "110c33af-d8ea-4749-94f9-97b7525c9479", "user_id": "33"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(110c33af-d8ea-4749-94f9-97b7525c9479, shreya@habilelabs.io) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(110c33af-d8ea-4749-94f9-97b7525c9479, shreya@habilelabs.io) already exists.\n\n"}
-----|10
{"failed_row": {"id": 118, "email": "deepak.kumar@habilelabs.io", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874094+00:00", "updated_at": "2024-11-26 12:40:15.874095+00:00", "created_at": "2024-11-26 12:40:15.874096+00:00", "invitation_accepted": true, "organization_id": "8081574f-0b2a-469f-86e7-a5be7f27c87a", "user_id": "34"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(8081574f-0b2a-469f-86e7-a5be7f27c87a, deepak.kumar@habilelabs.io) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(8081574f-0b2a-469f-86e7-a5be7f27c87a, deepak.kumar@habilelabs.io) already exists.\n\n"}
-----|10
{"failed_row": {"id": 119, "email": "deepak.kumar@habilelabs.io", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874098+00:00", "updated_at": "2024-11-26 12:40:15.874099+00:00", "created_at": "2024-11-26 12:40:15.874100+00:00", "invitation_accepted": true, "organization_id": "8081574f-0b2a-469f-86e7-a5be7f27c87a", "user_id": "34"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(8081574f-0b2a-469f-86e7-a5be7f27c87a, deepak.kumar@habilelabs.io) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(8081574f-0b2a-469f-86e7-a5be7f27c87a, deepak.kumar@habilelabs.io) already exists.\n\n"}
-----|10
{"failed_row": {"id": 120, "email": "deepak.kumar@habilelabs.io", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874102+00:00", "updated_at": "2024-11-26 12:40:15.874103+00:00", "created_at": "2024-11-26 12:40:15.874104+00:00", "invitation_accepted": true, "organization_id": "8081574f-0b2a-469f-86e7-a5be7f27c87a", "user_id": "34"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(8081574f-0b2a-469f-86e7-a5be7f27c87a, deepak.kumar@habilelabs.io) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(8081574f-0b2a-469f-86e7-a5be7f27c87a, deepak.kumar@habilelabs.io) already exists.\n\n"}
-----|10
{"failed_row": {"id": 121, "email": "deepak.kumar@habilelabs.io", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874106+00:00", "updated_at": "2024-11-26 12:40:15.874107+00:00", "created_at": "2024-11-26 12:40:15.874109+00:00", "invitation_accepted": true, "organization_id": "8081574f-0b2a-469f-86e7-a5be7f27c87a", "user_id": "34"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(8081574f-0b2a-469f-86e7-a5be7f27c87a, deepak.kumar@habilelabs.io) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(8081574f-0b2a-469f-86e7-a5be7f27c87a, deepak.kumar@habilelabs.io) already exists.\n\n"}
-----|10
{"failed_row": {"id": 130, "email": "gaurang.sharma@habilelabs.io", "role": "owner", "added_to_organization": "2024-11-26 12:40:15.874146+00:00", "updated_at": "2024-11-26 12:40:15.874147+00:00", "created_at": "2024-11-26 12:40:15.874149+00:00", "invitation_accepted": true, "organization_id": "16e27561-4313-4eac-b744-c807e1209cf6", "user_id": "45"}, "error": "duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(16e27561-4313-4eac-b744-c807e1209cf6, gaurang.sharma@habilelabs.io) already exists.\n", "traceback": "Traceback (most recent call last):\n  File \"/home/nsp/Desktop/proGPT/data_migrations/utils.py\", line 149, in load_data_into_table\n    cur.execute(insert_query, rows_to_insert)\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint \"accounts_organizationmember_organization_id_email_d648f3bc_uniq\"\nDETAIL:  Key (organization_id, email)=(16e27561-4313-4eac-b744-c807e1209cf6, gaurang.sharma@habilelabs.io) already exists.\n\n"}
-----|10
